// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: cache/v1/cache.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_cache_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_cache_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetTtl() *timestamppb.Timestamp {
	if x != nil {
		return x.Ttl
	}
	return nil
}

var File_cache_v1_cache_proto protoreflect.FileDescriptor

const file_cache_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x14cache/v1/cache.proto\x12\bcache.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12,\n" +
	"\x03ttl\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03ttlB.Z,github.com/trevatk/tbd/lib/protocol/cache/v1b\x06proto3"

var (
	file_cache_v1_cache_proto_rawDescOnce sync.Once
	file_cache_v1_cache_proto_rawDescData []byte
)

func file_cache_v1_cache_proto_rawDescGZIP() []byte {
	file_cache_v1_cache_proto_rawDescOnce.Do(func() {
		file_cache_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_v1_cache_proto_rawDesc), len(file_cache_v1_cache_proto_rawDesc)))
	})
	return file_cache_v1_cache_proto_rawDescData
}

var file_cache_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cache_v1_cache_proto_goTypes = []any{
	(*Entry)(nil),                 // 0: cache.v1.Entry
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_cache_v1_cache_proto_depIdxs = []int32{
	1, // 0: cache.v1.Entry.ttl:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cache_v1_cache_proto_init() }
func file_cache_v1_cache_proto_init() {
	if File_cache_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_v1_cache_proto_rawDesc), len(file_cache_v1_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cache_v1_cache_proto_goTypes,
		DependencyIndexes: file_cache_v1_cache_proto_depIdxs,
		MessageInfos:      file_cache_v1_cache_proto_msgTypes,
	}.Build()
	File_cache_v1_cache_proto = out.File
	file_cache_v1_cache_proto_goTypes = nil
	file_cache_v1_cache_proto_depIdxs = nil
}
