// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: vault/v1/vault_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnsealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealRequest) Reset() {
	*x = UnsealRequest{}
	mi := &file_vault_v1_vault_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealRequest) ProtoMessage() {}

func (x *UnsealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealRequest.ProtoReflect.Descriptor instead.
func (*UnsealRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_service_proto_rawDescGZIP(), []int{0}
}

type UnsealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealResponse) Reset() {
	*x = UnsealResponse{}
	mi := &file_vault_v1_vault_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealResponse) ProtoMessage() {}

func (x *UnsealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealResponse.ProtoReflect.Descriptor instead.
func (*UnsealResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_service_proto_rawDescGZIP(), []int{1}
}

var File_vault_v1_vault_service_proto protoreflect.FileDescriptor

const file_vault_v1_vault_service_proto_rawDesc = "" +
	"\n" +
	"\x1cvault/v1/vault_service.proto\x12\bvault.v1\"\x0f\n" +
	"\rUnsealRequest\"\x10\n" +
	"\x0eUnsealResponse2M\n" +
	"\fVaultService\x12=\n" +
	"\x06Unseal\x12\x17.vault.v1.UnsealRequest\x1a\x18.vault.v1.UnsealResponse\"\x00B\"Z soft.structx.io/idp/api/vault/v1b\x06proto3"

var (
	file_vault_v1_vault_service_proto_rawDescOnce sync.Once
	file_vault_v1_vault_service_proto_rawDescData []byte
)

func file_vault_v1_vault_service_proto_rawDescGZIP() []byte {
	file_vault_v1_vault_service_proto_rawDescOnce.Do(func() {
		file_vault_v1_vault_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_v1_vault_service_proto_rawDesc), len(file_vault_v1_vault_service_proto_rawDesc)))
	})
	return file_vault_v1_vault_service_proto_rawDescData
}

var file_vault_v1_vault_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vault_v1_vault_service_proto_goTypes = []any{
	(*UnsealRequest)(nil),  // 0: vault.v1.UnsealRequest
	(*UnsealResponse)(nil), // 1: vault.v1.UnsealResponse
}
var file_vault_v1_vault_service_proto_depIdxs = []int32{
	0, // 0: vault.v1.VaultService.Unseal:input_type -> vault.v1.UnsealRequest
	1, // 1: vault.v1.VaultService.Unseal:output_type -> vault.v1.UnsealResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vault_v1_vault_service_proto_init() }
func file_vault_v1_vault_service_proto_init() {
	if File_vault_v1_vault_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_v1_vault_service_proto_rawDesc), len(file_vault_v1_vault_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_v1_vault_service_proto_goTypes,
		DependencyIndexes: file_vault_v1_vault_service_proto_depIdxs,
		MessageInfos:      file_vault_v1_vault_service_proto_msgTypes,
	}.Build()
	File_vault_v1_vault_service_proto = out.File
	file_vault_v1_vault_service_proto_goTypes = nil
	file_vault_v1_vault_service_proto_depIdxs = nil
}
