// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dns/authoritative/v1/authoritative_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateZoneRequest) Reset() {
	*x = CreateZoneRequest{}
	mi := &file_dns_authoritative_v1_authoritative_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateZoneRequest) ProtoMessage() {}

func (x *CreateZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_authoritative_v1_authoritative_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateZoneRequest.ProtoReflect.Descriptor instead.
func (*CreateZoneRequest) Descriptor() ([]byte, []int) {
	return file_dns_authoritative_v1_authoritative_service_proto_rawDescGZIP(), []int{0}
}

type CreateZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateZoneResponse) Reset() {
	*x = CreateZoneResponse{}
	mi := &file_dns_authoritative_v1_authoritative_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateZoneResponse) ProtoMessage() {}

func (x *CreateZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_authoritative_v1_authoritative_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateZoneResponse.ProtoReflect.Descriptor instead.
func (*CreateZoneResponse) Descriptor() ([]byte, []int) {
	return file_dns_authoritative_v1_authoritative_service_proto_rawDescGZIP(), []int{1}
}

type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_dns_authoritative_v1_authoritative_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_authoritative_v1_authoritative_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_dns_authoritative_v1_authoritative_service_proto_rawDescGZIP(), []int{2}
}

type CreateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordResponse) Reset() {
	*x = CreateRecordResponse{}
	mi := &file_dns_authoritative_v1_authoritative_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResponse) ProtoMessage() {}

func (x *CreateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_authoritative_v1_authoritative_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateRecordResponse) Descriptor() ([]byte, []int) {
	return file_dns_authoritative_v1_authoritative_service_proto_rawDescGZIP(), []int{3}
}

var File_dns_authoritative_v1_authoritative_service_proto protoreflect.FileDescriptor

const file_dns_authoritative_v1_authoritative_service_proto_rawDesc = "" +
	"\n" +
	"0dns/authoritative/v1/authoritative_service.proto\x12\x14dns.authoritative.v1\"\x13\n" +
	"\x11CreateZoneRequest\"\x14\n" +
	"\x12CreateZoneResponse\"\x15\n" +
	"\x13CreateRecordRequest\"\x16\n" +
	"\x14CreateRecordResponse2\xe2\x01\n" +
	"\x14AuthoritativeService\x12a\n" +
	"\n" +
	"CreateZone\x12'.dns.authoritative.v1.CreateZoneRequest\x1a(.dns.authoritative.v1.CreateZoneResponse\"\x00\x12g\n" +
	"\fCreateRecord\x12).dns.authoritative.v1.CreateRecordRequest\x1a*.dns.authoritative.v1.CreateRecordResponse\"\x00B6Z4github.structx/tbd/lib/protocol/dns/authoritative/v1b\x06proto3"

var (
	file_dns_authoritative_v1_authoritative_service_proto_rawDescOnce sync.Once
	file_dns_authoritative_v1_authoritative_service_proto_rawDescData []byte
)

func file_dns_authoritative_v1_authoritative_service_proto_rawDescGZIP() []byte {
	file_dns_authoritative_v1_authoritative_service_proto_rawDescOnce.Do(func() {
		file_dns_authoritative_v1_authoritative_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dns_authoritative_v1_authoritative_service_proto_rawDesc), len(file_dns_authoritative_v1_authoritative_service_proto_rawDesc)))
	})
	return file_dns_authoritative_v1_authoritative_service_proto_rawDescData
}

var file_dns_authoritative_v1_authoritative_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dns_authoritative_v1_authoritative_service_proto_goTypes = []any{
	(*CreateZoneRequest)(nil),    // 0: dns.authoritative.v1.CreateZoneRequest
	(*CreateZoneResponse)(nil),   // 1: dns.authoritative.v1.CreateZoneResponse
	(*CreateRecordRequest)(nil),  // 2: dns.authoritative.v1.CreateRecordRequest
	(*CreateRecordResponse)(nil), // 3: dns.authoritative.v1.CreateRecordResponse
}
var file_dns_authoritative_v1_authoritative_service_proto_depIdxs = []int32{
	0, // 0: dns.authoritative.v1.AuthoritativeService.CreateZone:input_type -> dns.authoritative.v1.CreateZoneRequest
	2, // 1: dns.authoritative.v1.AuthoritativeService.CreateRecord:input_type -> dns.authoritative.v1.CreateRecordRequest
	1, // 2: dns.authoritative.v1.AuthoritativeService.CreateZone:output_type -> dns.authoritative.v1.CreateZoneResponse
	3, // 3: dns.authoritative.v1.AuthoritativeService.CreateRecord:output_type -> dns.authoritative.v1.CreateRecordResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dns_authoritative_v1_authoritative_service_proto_init() }
func file_dns_authoritative_v1_authoritative_service_proto_init() {
	if File_dns_authoritative_v1_authoritative_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dns_authoritative_v1_authoritative_service_proto_rawDesc), len(file_dns_authoritative_v1_authoritative_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dns_authoritative_v1_authoritative_service_proto_goTypes,
		DependencyIndexes: file_dns_authoritative_v1_authoritative_service_proto_depIdxs,
		MessageInfos:      file_dns_authoritative_v1_authoritative_service_proto_msgTypes,
	}.Build()
	File_dns_authoritative_v1_authoritative_service_proto = out.File
	file_dns_authoritative_v1_authoritative_service_proto_goTypes = nil
	file_dns_authoritative_v1_authoritative_service_proto_depIdxs = nil
}
