// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: audit/v1/audit_service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDecisionRequest) Reset() {
	*x = CreateDecisionRequest{}
	mi := &file_audit_v1_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecisionRequest) ProtoMessage() {}

func (x *CreateDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecisionRequest.ProtoReflect.Descriptor instead.
func (*CreateDecisionRequest) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_service_proto_rawDescGZIP(), []int{0}
}

type CreateDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDecisionResponse) Reset() {
	*x = CreateDecisionResponse{}
	mi := &file_audit_v1_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecisionResponse) ProtoMessage() {}

func (x *CreateDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecisionResponse.ProtoReflect.Descriptor instead.
func (*CreateDecisionResponse) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_service_proto_rawDescGZIP(), []int{1}
}

type ListDecisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsRequest) Reset() {
	*x = ListDecisionsRequest{}
	mi := &file_audit_v1_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsRequest) ProtoMessage() {}

func (x *ListDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsRequest.ProtoReflect.Descriptor instead.
func (*ListDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListDecisionsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDecisionsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Tx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Sig           string                 `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tx) Reset() {
	*x = Tx{}
	mi := &file_audit_v1_audit_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_service_proto_rawDescGZIP(), []int{3}
}

func (x *Tx) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Tx) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Tx) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Tx) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

type ListDecisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []*Tx                  `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsResponse) Reset() {
	*x = ListDecisionsResponse{}
	mi := &file_audit_v1_audit_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsResponse) ProtoMessage() {}

func (x *ListDecisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsResponse.ProtoReflect.Descriptor instead.
func (*ListDecisionsResponse) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListDecisionsResponse) GetTxs() []*Tx {
	if x != nil {
		return x.Txs
	}
	return nil
}

var File_audit_v1_audit_service_proto protoreflect.FileDescriptor

const file_audit_v1_audit_service_proto_rawDesc = "" +
	"\n" +
	"\x1caudit/v1/audit_service.proto\x12\baudit.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n" +
	"\x15CreateDecisionRequest\"\x18\n" +
	"\x16CreateDecisionResponse\"D\n" +
	"\x14ListDecisionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"N\n" +
	"\x02Tx\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x10\n" +
	"\x03sig\x18\x04 \x01(\tR\x03sig\"7\n" +
	"\x15ListDecisionsResponse\x12\x1e\n" +
	"\x03txs\x18\x01 \x03(\v2\f.audit.v1.TxR\x03txs2\xa9\x01\n" +
	"\fAuditService\x12E\n" +
	"\bDecision\x12\x1f.audit.v1.CreateDecisionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\rListDecisions\x12\x1e.audit.v1.ListDecisionsRequest\x1a\x1f.audit.v1.ListDecisionsResponse\"\x00B%Z#github.com/structx/idp/api/audit/v1b\x06proto3"

var (
	file_audit_v1_audit_service_proto_rawDescOnce sync.Once
	file_audit_v1_audit_service_proto_rawDescData []byte
)

func file_audit_v1_audit_service_proto_rawDescGZIP() []byte {
	file_audit_v1_audit_service_proto_rawDescOnce.Do(func() {
		file_audit_v1_audit_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_v1_audit_service_proto_rawDesc), len(file_audit_v1_audit_service_proto_rawDesc)))
	})
	return file_audit_v1_audit_service_proto_rawDescData
}

var file_audit_v1_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_audit_v1_audit_service_proto_goTypes = []any{
	(*CreateDecisionRequest)(nil),  // 0: audit.v1.CreateDecisionRequest
	(*CreateDecisionResponse)(nil), // 1: audit.v1.CreateDecisionResponse
	(*ListDecisionsRequest)(nil),   // 2: audit.v1.ListDecisionsRequest
	(*Tx)(nil),                     // 3: audit.v1.Tx
	(*ListDecisionsResponse)(nil),  // 4: audit.v1.ListDecisionsResponse
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_audit_v1_audit_service_proto_depIdxs = []int32{
	3, // 0: audit.v1.ListDecisionsResponse.txs:type_name -> audit.v1.Tx
	0, // 1: audit.v1.AuditService.Decision:input_type -> audit.v1.CreateDecisionRequest
	2, // 2: audit.v1.AuditService.ListDecisions:input_type -> audit.v1.ListDecisionsRequest
	5, // 3: audit.v1.AuditService.Decision:output_type -> google.protobuf.Empty
	4, // 4: audit.v1.AuditService.ListDecisions:output_type -> audit.v1.ListDecisionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_audit_v1_audit_service_proto_init() }
func file_audit_v1_audit_service_proto_init() {
	if File_audit_v1_audit_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_v1_audit_service_proto_rawDesc), len(file_audit_v1_audit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_v1_audit_service_proto_goTypes,
		DependencyIndexes: file_audit_v1_audit_service_proto_depIdxs,
		MessageInfos:      file_audit_v1_audit_service_proto_msgTypes,
	}.Build()
	File_audit_v1_audit_service_proto = out.File
	file_audit_v1_audit_service_proto_goTypes = nil
	file_audit_v1_audit_service_proto_depIdxs = nil
}
