// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: chat/v1/chat_service.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThreadRequest) Reset() {
	*x = CreateThreadRequest{}
	mi := &file_chat_v1_chat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreadRequest) ProtoMessage() {}

func (x *CreateThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreadRequest.ProtoReflect.Descriptor instead.
func (*CreateThreadRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateThreadRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CreateThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThreadResponse) Reset() {
	*x = CreateThreadResponse{}
	mi := &file_chat_v1_chat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreadResponse) ProtoMessage() {}

func (x *CreateThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreadResponse.ProtoReflect.Descriptor instead.
func (*CreateThreadResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateThreadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateThreadResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_chat_v1_chat_service_proto protoreflect.FileDescriptor

const file_chat_v1_chat_service_proto_rawDesc = "" +
	"\n" +
	"\x1achat/v1/chat_service.proto\x12\achat.v1\"8\n" +
	"\x13CreateThreadRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"I\n" +
	"\x14CreateThreadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName2\\\n" +
	"\vChatService\x12M\n" +
	"\fCreateThread\x12\x1c.chat.v1.CreateThreadRequest\x1a\x1d.chat.v1.CreateThreadResponse\"\x00B-Z+github.com/trevatk/tbd/lib/protocol/chat/v1b\x06proto3"

var (
	file_chat_v1_chat_service_proto_rawDescOnce sync.Once
	file_chat_v1_chat_service_proto_rawDescData []byte
)

func file_chat_v1_chat_service_proto_rawDescGZIP() []byte {
	file_chat_v1_chat_service_proto_rawDescOnce.Do(func() {
		file_chat_v1_chat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_v1_chat_service_proto_rawDesc), len(file_chat_v1_chat_service_proto_rawDesc)))
	})
	return file_chat_v1_chat_service_proto_rawDescData
}

var file_chat_v1_chat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_v1_chat_service_proto_goTypes = []any{
	(*CreateThreadRequest)(nil),  // 0: chat.v1.CreateThreadRequest
	(*CreateThreadResponse)(nil), // 1: chat.v1.CreateThreadResponse
}
var file_chat_v1_chat_service_proto_depIdxs = []int32{
	0, // 0: chat.v1.ChatService.CreateThread:input_type -> chat.v1.CreateThreadRequest
	1, // 1: chat.v1.ChatService.CreateThread:output_type -> chat.v1.CreateThreadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_v1_chat_service_proto_init() }
func file_chat_v1_chat_service_proto_init() {
	if File_chat_v1_chat_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_v1_chat_service_proto_rawDesc), len(file_chat_v1_chat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_v1_chat_service_proto_goTypes,
		DependencyIndexes: file_chat_v1_chat_service_proto_depIdxs,
		MessageInfos:      file_chat_v1_chat_service_proto_msgTypes,
	}.Build()
	File_chat_v1_chat_service_proto = out.File
	file_chat_v1_chat_service_proto_goTypes = nil
	file_chat_v1_chat_service_proto_depIdxs = nil
}
