{{- if .Values.wellknown.enabled }}
apiVersion: v1
kind: Deployment
metadata:
  name: wellknown
  namespace: tbd
spec:
  template:
    metadata:
    spec:
      containers:
        - name: wellknown
          image: {{ .Values.wellknown.image.registry }}/{{ .Values.wellknown.image.repository }}/{{.Values.wellknown.image.tag }}
{{- end }}