// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: identities/v1/identities_service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RealmCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealmCreate) Reset() {
	*x = RealmCreate{}
	mi := &file_identities_v1_identities_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealmCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealmCreate) ProtoMessage() {}

func (x *RealmCreate) ProtoReflect() protoreflect.Message {
	mi := &file_identities_v1_identities_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealmCreate.ProtoReflect.Descriptor instead.
func (*RealmCreate) Descriptor() ([]byte, []int) {
	return file_identities_v1_identities_service_proto_rawDescGZIP(), []int{0}
}

func (x *RealmCreate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CreateRealmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Create        *RealmCreate           `protobuf:"bytes,1,opt,name=create,proto3" json:"create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRealmRequest) Reset() {
	*x = CreateRealmRequest{}
	mi := &file_identities_v1_identities_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmRequest) ProtoMessage() {}

func (x *CreateRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identities_v1_identities_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmRequest.ProtoReflect.Descriptor instead.
func (*CreateRealmRequest) Descriptor() ([]byte, []int) {
	return file_identities_v1_identities_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRealmRequest) GetCreate() *RealmCreate {
	if x != nil {
		return x.Create
	}
	return nil
}

type Realm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Realm) Reset() {
	*x = Realm{}
	mi := &file_identities_v1_identities_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Realm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Realm) ProtoMessage() {}

func (x *Realm) ProtoReflect() protoreflect.Message {
	mi := &file_identities_v1_identities_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Realm.ProtoReflect.Descriptor instead.
func (*Realm) Descriptor() ([]byte, []int) {
	return file_identities_v1_identities_service_proto_rawDescGZIP(), []int{2}
}

func (x *Realm) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Realm) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CreateRealmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Realm         *Realm                 `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRealmResponse) Reset() {
	*x = CreateRealmResponse{}
	mi := &file_identities_v1_identities_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmResponse) ProtoMessage() {}

func (x *CreateRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identities_v1_identities_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmResponse.ProtoReflect.Descriptor instead.
func (*CreateRealmResponse) Descriptor() ([]byte, []int) {
	return file_identities_v1_identities_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRealmResponse) GetRealm() *Realm {
	if x != nil {
		return x.Realm
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	RealmHash     string                 `protobuf:"bytes,2,opt,name=realm_hash,json=realmHash,proto3" json:"realm_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_identities_v1_identities_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identities_v1_identities_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_identities_v1_identities_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetRealmHash() string {
	if x != nil {
		return x.RealmHash
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_identities_v1_identities_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identities_v1_identities_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_identities_v1_identities_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_identities_v1_identities_service_proto protoreflect.FileDescriptor

const file_identities_v1_identities_service_proto_rawDesc = "" +
	"\n" +
	"&identities/v1/identities_service.proto\x12\ridentities.v1\x1a\x1bbuf/validate/validate.proto\"0\n" +
	"\vRealmCreate\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"H\n" +
	"\x12CreateRealmRequest\x122\n" +
	"\x06create\x18\x01 \x01(\v2\x1a.identities.v1.RealmCreateR\x06create\">\n" +
	"\x05Realm\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"A\n" +
	"\x13CreateRealmResponse\x12*\n" +
	"\x05realm\x18\x01 \x01(\v2\x14.identities.v1.RealmR\x05realm\"Q\n" +
	"\x11CreateUserRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12\x1d\n" +
	"\n" +
	"realm_hash\x18\x02 \x01(\tR\trealmHash\"(\n" +
	"\x12CreateUserResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash2\xc0\x01\n" +
	"\x11IdentitiesService\x12V\n" +
	"\vCreateRealm\x12!.identities.v1.CreateRealmRequest\x1a\".identities.v1.CreateRealmResponse\"\x00\x12S\n" +
	"\n" +
	"CreateUser\x12 .identities.v1.CreateUserRequest\x1a!.identities.v1.CreateUserResponse\"\x00B*Z(github.com/structx/idp/api/identities/v1b\x06proto3"

var (
	file_identities_v1_identities_service_proto_rawDescOnce sync.Once
	file_identities_v1_identities_service_proto_rawDescData []byte
)

func file_identities_v1_identities_service_proto_rawDescGZIP() []byte {
	file_identities_v1_identities_service_proto_rawDescOnce.Do(func() {
		file_identities_v1_identities_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identities_v1_identities_service_proto_rawDesc), len(file_identities_v1_identities_service_proto_rawDesc)))
	})
	return file_identities_v1_identities_service_proto_rawDescData
}

var file_identities_v1_identities_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_identities_v1_identities_service_proto_goTypes = []any{
	(*RealmCreate)(nil),         // 0: identities.v1.RealmCreate
	(*CreateRealmRequest)(nil),  // 1: identities.v1.CreateRealmRequest
	(*Realm)(nil),               // 2: identities.v1.Realm
	(*CreateRealmResponse)(nil), // 3: identities.v1.CreateRealmResponse
	(*CreateUserRequest)(nil),   // 4: identities.v1.CreateUserRequest
	(*CreateUserResponse)(nil),  // 5: identities.v1.CreateUserResponse
}
var file_identities_v1_identities_service_proto_depIdxs = []int32{
	0, // 0: identities.v1.CreateRealmRequest.create:type_name -> identities.v1.RealmCreate
	2, // 1: identities.v1.CreateRealmResponse.realm:type_name -> identities.v1.Realm
	1, // 2: identities.v1.IdentitiesService.CreateRealm:input_type -> identities.v1.CreateRealmRequest
	4, // 3: identities.v1.IdentitiesService.CreateUser:input_type -> identities.v1.CreateUserRequest
	3, // 4: identities.v1.IdentitiesService.CreateRealm:output_type -> identities.v1.CreateRealmResponse
	5, // 5: identities.v1.IdentitiesService.CreateUser:output_type -> identities.v1.CreateUserResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identities_v1_identities_service_proto_init() }
func file_identities_v1_identities_service_proto_init() {
	if File_identities_v1_identities_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identities_v1_identities_service_proto_rawDesc), len(file_identities_v1_identities_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identities_v1_identities_service_proto_goTypes,
		DependencyIndexes: file_identities_v1_identities_service_proto_depIdxs,
		MessageInfos:      file_identities_v1_identities_service_proto_msgTypes,
	}.Build()
	File_identities_v1_identities_service_proto = out.File
	file_identities_v1_identities_service_proto_goTypes = nil
	file_identities_v1_identities_service_proto_depIdxs = nil
}
