// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wellknown/v1/wellknown_service.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	did "github.com/trevatk/tbd/lib/protocol/did/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDIDConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDIDConfigurationRequest) Reset() {
	*x = GetDIDConfigurationRequest{}
	mi := &file_wellknown_v1_wellknown_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDIDConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDIDConfigurationRequest) ProtoMessage() {}

func (x *GetDIDConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wellknown_v1_wellknown_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDIDConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetDIDConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_wellknown_v1_wellknown_service_proto_rawDescGZIP(), []int{0}
}

type GetDIDConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doc           *did.Document          `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDIDConfigurationResponse) Reset() {
	*x = GetDIDConfigurationResponse{}
	mi := &file_wellknown_v1_wellknown_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDIDConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDIDConfigurationResponse) ProtoMessage() {}

func (x *GetDIDConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wellknown_v1_wellknown_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDIDConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetDIDConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_wellknown_v1_wellknown_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDIDConfigurationResponse) GetDoc() *did.Document {
	if x != nil {
		return x.Doc
	}
	return nil
}

var File_wellknown_v1_wellknown_service_proto protoreflect.FileDescriptor

const file_wellknown_v1_wellknown_service_proto_rawDesc = "" +
	"\n" +
	"$wellknown/v1/wellknown_service.proto\x12\fwellknown.v1\x1a\x15did/v1/document.proto\"\x1c\n" +
	"\x1aGetDIDConfigurationRequest\"A\n" +
	"\x1bGetDIDConfigurationResponse\x12\"\n" +
	"\x03doc\x18\x01 \x01(\v2\x10.did.v1.DocumentR\x03doc2\x80\x01\n" +
	"\x10WellKnownService\x12l\n" +
	"\x13GetDIDConfiguration\x12(.wellknown.v1.GetDIDConfigurationRequest\x1a).wellknown.v1.GetDIDConfigurationResponse\"\x00B\xac\x01\n" +
	"\x10com.wellknown.v1B\x15WellknownServiceProtoP\x01Z0github.com/trevatk/tbd/lib/protocol/wellknown/v1\xa2\x02\x03WXX\xaa\x02\fWellknown.V1\xca\x02\fWellknown\\V1\xe2\x02\x18Wellknown\\V1\\GPBMetadata\xea\x02\rWellknown::V1b\x06proto3"

var (
	file_wellknown_v1_wellknown_service_proto_rawDescOnce sync.Once
	file_wellknown_v1_wellknown_service_proto_rawDescData []byte
)

func file_wellknown_v1_wellknown_service_proto_rawDescGZIP() []byte {
	file_wellknown_v1_wellknown_service_proto_rawDescOnce.Do(func() {
		file_wellknown_v1_wellknown_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wellknown_v1_wellknown_service_proto_rawDesc), len(file_wellknown_v1_wellknown_service_proto_rawDesc)))
	})
	return file_wellknown_v1_wellknown_service_proto_rawDescData
}

var file_wellknown_v1_wellknown_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wellknown_v1_wellknown_service_proto_goTypes = []any{
	(*GetDIDConfigurationRequest)(nil),  // 0: wellknown.v1.GetDIDConfigurationRequest
	(*GetDIDConfigurationResponse)(nil), // 1: wellknown.v1.GetDIDConfigurationResponse
	(*did.Document)(nil),                // 2: did.v1.Document
}
var file_wellknown_v1_wellknown_service_proto_depIdxs = []int32{
	2, // 0: wellknown.v1.GetDIDConfigurationResponse.doc:type_name -> did.v1.Document
	0, // 1: wellknown.v1.WellKnownService.GetDIDConfiguration:input_type -> wellknown.v1.GetDIDConfigurationRequest
	1, // 2: wellknown.v1.WellKnownService.GetDIDConfiguration:output_type -> wellknown.v1.GetDIDConfigurationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wellknown_v1_wellknown_service_proto_init() }
func file_wellknown_v1_wellknown_service_proto_init() {
	if File_wellknown_v1_wellknown_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wellknown_v1_wellknown_service_proto_rawDesc), len(file_wellknown_v1_wellknown_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wellknown_v1_wellknown_service_proto_goTypes,
		DependencyIndexes: file_wellknown_v1_wellknown_service_proto_depIdxs,
		MessageInfos:      file_wellknown_v1_wellknown_service_proto_msgTypes,
	}.Build()
	File_wellknown_v1_wellknown_service_proto = out.File
	file_wellknown_v1_wellknown_service_proto_goTypes = nil
	file_wellknown_v1_wellknown_service_proto_depIdxs = nil
}
