// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: wellknown/v1/wellknown_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WellKnownService_GetDIDConfiguration_FullMethodName = "/wellknown.v1.WellKnownService/GetDIDConfiguration"
)

// WellKnownServiceClient is the client API for WellKnownService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WellKnownServiceClient interface {
	GetDIDConfiguration(ctx context.Context, in *GetDIDConfigurationRequest, opts ...grpc.CallOption) (*GetDIDConfigurationResponse, error)
}

type wellKnownServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWellKnownServiceClient(cc grpc.ClientConnInterface) WellKnownServiceClient {
	return &wellKnownServiceClient{cc}
}

func (c *wellKnownServiceClient) GetDIDConfiguration(ctx context.Context, in *GetDIDConfigurationRequest, opts ...grpc.CallOption) (*GetDIDConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDIDConfigurationResponse)
	err := c.cc.Invoke(ctx, WellKnownService_GetDIDConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WellKnownServiceServer is the server API for WellKnownService service.
// All implementations must embed UnimplementedWellKnownServiceServer
// for forward compatibility.
type WellKnownServiceServer interface {
	GetDIDConfiguration(context.Context, *GetDIDConfigurationRequest) (*GetDIDConfigurationResponse, error)
	mustEmbedUnimplementedWellKnownServiceServer()
}

// UnimplementedWellKnownServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWellKnownServiceServer struct{}

func (UnimplementedWellKnownServiceServer) GetDIDConfiguration(context.Context, *GetDIDConfigurationRequest) (*GetDIDConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDIDConfiguration not implemented")
}
func (UnimplementedWellKnownServiceServer) mustEmbedUnimplementedWellKnownServiceServer() {}
func (UnimplementedWellKnownServiceServer) testEmbeddedByValue()                          {}

// UnsafeWellKnownServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WellKnownServiceServer will
// result in compilation errors.
type UnsafeWellKnownServiceServer interface {
	mustEmbedUnimplementedWellKnownServiceServer()
}

func RegisterWellKnownServiceServer(s grpc.ServiceRegistrar, srv WellKnownServiceServer) {
	// If the following call pancis, it indicates UnimplementedWellKnownServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WellKnownService_ServiceDesc, srv)
}

func _WellKnownService_GetDIDConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDIDConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WellKnownServiceServer).GetDIDConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WellKnownService_GetDIDConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WellKnownServiceServer).GetDIDConfiguration(ctx, req.(*GetDIDConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WellKnownService_ServiceDesc is the grpc.ServiceDesc for WellKnownService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WellKnownService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wellknown.v1.WellKnownService",
	HandlerType: (*WellKnownServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDIDConfiguration",
			Handler:    _WellKnownService_GetDIDConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wellknown/v1/wellknown_service.proto",
}
