// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wellknown/v1/wellknown_service.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_wellknown_v1_wellknown_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wellknown_v1_wellknown_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_wellknown_v1_wellknown_service_proto_rawDescGZIP(), []int{0}
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_wellknown_v1_wellknown_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wellknown_v1_wellknown_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_wellknown_v1_wellknown_service_proto_rawDescGZIP(), []int{1}
}

var File_wellknown_v1_wellknown_service_proto protoreflect.FileDescriptor

const file_wellknown_v1_wellknown_service_proto_rawDesc = "" +
	"\n" +
	"$wellknown/v1/wellknown_service.proto\x12\fwellknown.v1\"\x0f\n" +
	"\rVerifyRequest\"\x10\n" +
	"\x0eVerifyResponse2Y\n" +
	"\x10WellKnownService\x12E\n" +
	"\x06Verify\x12\x1b.wellknown.v1.VerifyRequest\x1a\x1c.wellknown.v1.VerifyResponse\"\x00B2Z0github.com/trevatk/tbd/lib/protocol/wellknown/v1b\x06proto3"

var (
	file_wellknown_v1_wellknown_service_proto_rawDescOnce sync.Once
	file_wellknown_v1_wellknown_service_proto_rawDescData []byte
)

func file_wellknown_v1_wellknown_service_proto_rawDescGZIP() []byte {
	file_wellknown_v1_wellknown_service_proto_rawDescOnce.Do(func() {
		file_wellknown_v1_wellknown_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wellknown_v1_wellknown_service_proto_rawDesc), len(file_wellknown_v1_wellknown_service_proto_rawDesc)))
	})
	return file_wellknown_v1_wellknown_service_proto_rawDescData
}

var file_wellknown_v1_wellknown_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wellknown_v1_wellknown_service_proto_goTypes = []any{
	(*VerifyRequest)(nil),  // 0: wellknown.v1.VerifyRequest
	(*VerifyResponse)(nil), // 1: wellknown.v1.VerifyResponse
}
var file_wellknown_v1_wellknown_service_proto_depIdxs = []int32{
	0, // 0: wellknown.v1.WellKnownService.Verify:input_type -> wellknown.v1.VerifyRequest
	1, // 1: wellknown.v1.WellKnownService.Verify:output_type -> wellknown.v1.VerifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wellknown_v1_wellknown_service_proto_init() }
func file_wellknown_v1_wellknown_service_proto_init() {
	if File_wellknown_v1_wellknown_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wellknown_v1_wellknown_service_proto_rawDesc), len(file_wellknown_v1_wellknown_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wellknown_v1_wellknown_service_proto_goTypes,
		DependencyIndexes: file_wellknown_v1_wellknown_service_proto_depIdxs,
		MessageInfos:      file_wellknown_v1_wellknown_service_proto_msgTypes,
	}.Build()
	File_wellknown_v1_wellknown_service_proto = out.File
	file_wellknown_v1_wellknown_service_proto_goTypes = nil
	file_wellknown_v1_wellknown_service_proto_depIdxs = nil
}
