// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dns/resolver/v1/resolver_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DNSResolverService_Resolve_FullMethodName = "/dns.resolver.v1.DNSResolverService/Resolve"
)

// DNSResolverServiceClient is the client API for DNSResolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DNSResolverServiceClient interface {
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type dNSResolverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSResolverServiceClient(cc grpc.ClientConnInterface) DNSResolverServiceClient {
	return &dNSResolverServiceClient{cc}
}

func (c *dNSResolverServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, DNSResolverService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DNSResolverServiceServer is the server API for DNSResolverService service.
// All implementations must embed UnimplementedDNSResolverServiceServer
// for forward compatibility.
type DNSResolverServiceServer interface {
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	mustEmbedUnimplementedDNSResolverServiceServer()
}

// UnimplementedDNSResolverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDNSResolverServiceServer struct{}

func (UnimplementedDNSResolverServiceServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedDNSResolverServiceServer) mustEmbedUnimplementedDNSResolverServiceServer() {}
func (UnimplementedDNSResolverServiceServer) testEmbeddedByValue()                            {}

// UnsafeDNSResolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSResolverServiceServer will
// result in compilation errors.
type UnsafeDNSResolverServiceServer interface {
	mustEmbedUnimplementedDNSResolverServiceServer()
}

func RegisterDNSResolverServiceServer(s grpc.ServiceRegistrar, srv DNSResolverServiceServer) {
	// If the following call pancis, it indicates UnimplementedDNSResolverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DNSResolverService_ServiceDesc, srv)
}

func _DNSResolverService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSResolverServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSResolverService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSResolverServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DNSResolverService_ServiceDesc is the grpc.ServiceDesc for DNSResolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSResolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dns.resolver.v1.DNSResolverService",
	HandlerType: (*DNSResolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _DNSResolverService_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dns/resolver/v1/resolver_service.proto",
}
