// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: did/v1/document.proto

package did

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Context              string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id                   string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Controller           []string               `protobuf:"bytes,3,rep,name=controller,proto3" json:"controller,omitempty"`
	AlsoKnownAs          []string               `protobuf:"bytes,4,rep,name=also_known_as,json=alsoKnownAs,proto3" json:"also_known_as,omitempty"`
	Service              *Service               `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	VerificationMethod   *VerificationMethod    `protobuf:"bytes,6,opt,name=verification_method,json=verificationMethod,proto3" json:"verification_method,omitempty"`
	Authentication       []*Authentication      `protobuf:"bytes,7,rep,name=authentication,proto3" json:"authentication,omitempty"`
	AssertionMethod      []string               `protobuf:"bytes,8,rep,name=assertion_method,json=assertionMethod,proto3" json:"assertion_method,omitempty"`
	KeyAgreement         []string               `protobuf:"bytes,9,rep,name=key_agreement,json=keyAgreement,proto3" json:"key_agreement,omitempty"`
	CapabilityInvocation []string               `protobuf:"bytes,10,rep,name=capability_invocation,json=capabilityInvocation,proto3" json:"capability_invocation,omitempty"`
	CapabilityDelegation []string               `protobuf:"bytes,11,rep,name=capability_delegation,json=capabilityDelegation,proto3" json:"capability_delegation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_did_v1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_did_v1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_did_v1_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetController() []string {
	if x != nil {
		return x.Controller
	}
	return nil
}

func (x *Document) GetAlsoKnownAs() []string {
	if x != nil {
		return x.AlsoKnownAs
	}
	return nil
}

func (x *Document) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Document) GetVerificationMethod() *VerificationMethod {
	if x != nil {
		return x.VerificationMethod
	}
	return nil
}

func (x *Document) GetAuthentication() []*Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *Document) GetAssertionMethod() []string {
	if x != nil {
		return x.AssertionMethod
	}
	return nil
}

func (x *Document) GetKeyAgreement() []string {
	if x != nil {
		return x.KeyAgreement
	}
	return nil
}

func (x *Document) GetCapabilityInvocation() []string {
	if x != nil {
		return x.CapabilityInvocation
	}
	return nil
}

func (x *Document) GetCapabilityDelegation() []string {
	if x != nil {
		return x.CapabilityDelegation
	}
	return nil
}

type Service struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ServiceEndpoint string                 `protobuf:"bytes,3,opt,name=service_endpoint,json=serviceEndpoint,proto3" json:"service_endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_did_v1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_did_v1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_did_v1_document_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Service) GetServiceEndpoint() string {
	if x != nil {
		return x.ServiceEndpoint
	}
	return ""
}

type VerificationMethod struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Controller         string                 `protobuf:"bytes,3,opt,name=controller,proto3" json:"controller,omitempty"`
	PublicKeyMultibase string                 `protobuf:"bytes,4,opt,name=public_key_multibase,json=publicKeyMultibase,proto3" json:"public_key_multibase,omitempty"`
	PublicKeyJwk       string                 `protobuf:"bytes,5,opt,name=public_key_jwk,json=publicKeyJwk,proto3" json:"public_key_jwk,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerificationMethod) Reset() {
	*x = VerificationMethod{}
	mi := &file_did_v1_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationMethod) ProtoMessage() {}

func (x *VerificationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_did_v1_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationMethod.ProtoReflect.Descriptor instead.
func (*VerificationMethod) Descriptor() ([]byte, []int) {
	return file_did_v1_document_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerificationMethod) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VerificationMethod) GetController() string {
	if x != nil {
		return x.Controller
	}
	return ""
}

func (x *VerificationMethod) GetPublicKeyMultibase() string {
	if x != nil {
		return x.PublicKeyMultibase
	}
	return ""
}

func (x *VerificationMethod) GetPublicKeyJwk() string {
	if x != nil {
		return x.PublicKeyJwk
	}
	return ""
}

type Authentication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MethodRef:
	//
	//	*Authentication_Method
	//	*Authentication_Reference
	MethodRef     isAuthentication_MethodRef `protobuf_oneof:"method_ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	mi := &file_did_v1_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_did_v1_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_did_v1_document_proto_rawDescGZIP(), []int{3}
}

func (x *Authentication) GetMethodRef() isAuthentication_MethodRef {
	if x != nil {
		return x.MethodRef
	}
	return nil
}

func (x *Authentication) GetMethod() string {
	if x != nil {
		if x, ok := x.MethodRef.(*Authentication_Method); ok {
			return x.Method
		}
	}
	return ""
}

func (x *Authentication) GetReference() *Service {
	if x != nil {
		if x, ok := x.MethodRef.(*Authentication_Reference); ok {
			return x.Reference
		}
	}
	return nil
}

type isAuthentication_MethodRef interface {
	isAuthentication_MethodRef()
}

type Authentication_Method struct {
	Method string `protobuf:"bytes,1,opt,name=method,proto3,oneof"`
}

type Authentication_Reference struct {
	Reference *Service `protobuf:"bytes,2,opt,name=reference,proto3,oneof"`
}

func (*Authentication_Method) isAuthentication_MethodRef() {}

func (*Authentication_Reference) isAuthentication_MethodRef() {}

var File_did_v1_document_proto protoreflect.FileDescriptor

const file_did_v1_document_proto_rawDesc = "" +
	"\n" +
	"\x15did/v1/document.proto\x12\x06did.v1\"\xea\x03\n" +
	"\bDocument\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"controller\x18\x03 \x03(\tR\n" +
	"controller\x12\"\n" +
	"\ralso_known_as\x18\x04 \x03(\tR\valsoKnownAs\x12)\n" +
	"\aservice\x18\x05 \x01(\v2\x0f.did.v1.ServiceR\aservice\x12K\n" +
	"\x13verification_method\x18\x06 \x01(\v2\x1a.did.v1.VerificationMethodR\x12verificationMethod\x12>\n" +
	"\x0eauthentication\x18\a \x03(\v2\x16.did.v1.AuthenticationR\x0eauthentication\x12)\n" +
	"\x10assertion_method\x18\b \x03(\tR\x0fassertionMethod\x12#\n" +
	"\rkey_agreement\x18\t \x03(\tR\fkeyAgreement\x123\n" +
	"\x15capability_invocation\x18\n" +
	" \x03(\tR\x14capabilityInvocation\x123\n" +
	"\x15capability_delegation\x18\v \x03(\tR\x14capabilityDelegation\"X\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12)\n" +
	"\x10service_endpoint\x18\x03 \x01(\tR\x0fserviceEndpoint\"\xb0\x01\n" +
	"\x12VerificationMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"controller\x18\x03 \x01(\tR\n" +
	"controller\x120\n" +
	"\x14public_key_multibase\x18\x04 \x01(\tR\x12publicKeyMultibase\x12$\n" +
	"\x0epublic_key_jwk\x18\x05 \x01(\tR\fpublicKeyJwk\"i\n" +
	"\x0eAuthentication\x12\x18\n" +
	"\x06method\x18\x01 \x01(\tH\x00R\x06method\x12/\n" +
	"\treference\x18\x02 \x01(\v2\x0f.did.v1.ServiceH\x00R\treferenceB\f\n" +
	"\n" +
	"method_refB)Z'github.com/trevatk/tbd/lib/protocol/didb\x06proto3"

var (
	file_did_v1_document_proto_rawDescOnce sync.Once
	file_did_v1_document_proto_rawDescData []byte
)

func file_did_v1_document_proto_rawDescGZIP() []byte {
	file_did_v1_document_proto_rawDescOnce.Do(func() {
		file_did_v1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_did_v1_document_proto_rawDesc), len(file_did_v1_document_proto_rawDesc)))
	})
	return file_did_v1_document_proto_rawDescData
}

var file_did_v1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_did_v1_document_proto_goTypes = []any{
	(*Document)(nil),           // 0: did.v1.Document
	(*Service)(nil),            // 1: did.v1.Service
	(*VerificationMethod)(nil), // 2: did.v1.VerificationMethod
	(*Authentication)(nil),     // 3: did.v1.Authentication
}
var file_did_v1_document_proto_depIdxs = []int32{
	1, // 0: did.v1.Document.service:type_name -> did.v1.Service
	2, // 1: did.v1.Document.verification_method:type_name -> did.v1.VerificationMethod
	3, // 2: did.v1.Document.authentication:type_name -> did.v1.Authentication
	1, // 3: did.v1.Authentication.reference:type_name -> did.v1.Service
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_did_v1_document_proto_init() }
func file_did_v1_document_proto_init() {
	if File_did_v1_document_proto != nil {
		return
	}
	file_did_v1_document_proto_msgTypes[3].OneofWrappers = []any{
		(*Authentication_Method)(nil),
		(*Authentication_Reference)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_did_v1_document_proto_rawDesc), len(file_did_v1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_did_v1_document_proto_goTypes,
		DependencyIndexes: file_did_v1_document_proto_depIdxs,
		MessageInfos:      file_did_v1_document_proto_msgTypes,
	}.Build()
	File_did_v1_document_proto = out.File
	file_did_v1_document_proto_goTypes = nil
	file_did_v1_document_proto_depIdxs = nil
}
