// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/trevatk/tbd/dns/internal/authoritative (interfaces: Kv)
//
// Generated by this command:
//
//	mockgen -destination mock_kv_test.go -package authoritative . Kv
//

// Package authoritative is a generated GoMock package.
package authoritative

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKv is a mock of Kv interface.
type MockKv struct {
	ctrl     *gomock.Controller
	recorder *MockKvMockRecorder
	isgomock struct{}
}

// MockKvMockRecorder is the mock recorder for MockKv.
type MockKvMockRecorder struct {
	mock *MockKv
}

// NewMockKv creates a new mock instance.
func NewMockKv(ctrl *gomock.Controller) *MockKv {
	mock := &MockKv{ctrl: ctrl}
	mock.recorder = &MockKvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKv) EXPECT() *MockKvMockRecorder {
	return m.recorder
}

// get mocks base method.
func (m *MockKv) get(arg0 string) (record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "get", arg0)
	ret0, _ := ret[0].(record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// get indicates an expected call of get.
func (mr *MockKvMockRecorder) get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "get", reflect.TypeOf((*MockKv)(nil).get), arg0)
}

// set mocks base method.
func (m *MockKv) set(arg0 string, arg1 record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "set", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// set indicates an expected call of set.
func (mr *MockKvMockRecorder) set(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "set", reflect.TypeOf((*MockKv)(nil).set), arg0, arg1)
}
