name: Trivy Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  schedule:
    # run every night at midnight
    - cron: '0 0 * * *'

env:
  GO_VERSION: '1.24.4'

jobs:
  
  detect-modules:
      runs-on: ubuntu-latest
      outputs:
        modules: ${{ steps.set-modules.outputs.modules }}
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: ${{ env.GO_VERSION }}
        - id: set-modules
          run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT

  scan:
    permissions:
      contents: read
      security-events: write
      actions: read 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          exit-code: 0
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'