name = "air"
type = "cli"

[platform.linux]
download-file = "air_{version}_linux_{arch}.tar.gz"
checksum-file = "air_{version}_checksums.txt"

[platform.macos]
download-file = "air_{version}_darwin_{arch}.tar.gz"
checksum-file = "air_{version}_checksums.txt"

[platform.windows]
download-file = "air_{version}_windows_{arch}.tar.gz"
checksum-file = "air_{version}_checksums.txt"

[install]
checksum-url = "https://github.com/air-verse/air/releases/download/v{version}/{checksum_file}"
download-url = "https://github.com/air-verse/air/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
x86 = "386"

[resolve]
git-url = "https://github.com/air-verse/air"